apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: ${GF_POSTGRES_HOST:-postgres:5432}
    database: ${GF_POSTGRES_DB:-edrdb}
    user: ${GF_POSTGRES_USER:-edr}
    secureJsonData:
      password: ${GF_POSTGRES_PASSWORD:-password}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    editable: false
