//go:build darwin

package darwin

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"sync"

	"github.com/edr-platform/agent/internal/collector"
)

const (
	edrAnchorName = "edr_isolate"
	pfConfPath    = "/tmp/edr_isolate.conf"
)

// PFIsolationManager implements collector.IsolationManager using macOS pf (packet filter).
type PFIsolationManager struct {
	mu          sync.RWMutex
	isolated    bool
	edrServerIP string
	prevPFState bool // was pf enabled before isolation?
}

func NewPFIsolationManager(edrServerIP string) *PFIsolationManager {
	return &PFIsolationManager{edrServerIP: edrServerIP}
}

// Isolate applies pf rules using an anchor to block all traffic
// except the EDR server, DNS, and loopback.
func (m *PFIsolationManager) Isolate(allowedIPs []string, allowedPorts []uint16) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.isolated {
		return nil
	}

	// Save current pf state
	m.prevPFState = isPFEnabled()

	// Build pf anchor config
	allAllowed := append(allowedIPs, m.edrServerIP)
	conf := buildPFConfig(allAllowed)

	// Write anchor config
	if err := os.WriteFile(pfConfPath, []byte(conf), 0600); err != nil {
		return fmt.Errorf("write pf config: %w", err)
	}

	// Load anchor rules
	if err := runPF("pfctl", "-a", edrAnchorName, "-f", pfConfPath); err != nil {
		return fmt.Errorf("load pf anchor: %w", err)
	}

	// Enable pf if not already enabled
	if !m.prevPFState {
		if err := runPF("pfctl", "-e"); err != nil {
			return fmt.Errorf("enable pf: %w", err)
		}
	}

	// Add anchor to main pf ruleset
	mainConf := fmt.Sprintf("anchor \"%s\"\n", edrAnchorName)
	tmpMain := "/tmp/edr_main_anchor.conf"
	if err := os.WriteFile(tmpMain, []byte(mainConf), 0600); err != nil {
		return fmt.Errorf("write main anchor: %w", err)
	}
	if err := runPF("pfctl", "-f", tmpMain); err != nil {
		return fmt.Errorf("apply main anchor: %w", err)
	}

	m.isolated = true
	return nil
}

// Unisolate removes the EDR pf anchor.
func (m *PFIsolationManager) Unisolate() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if !m.isolated {
		return nil
	}

	// Flush anchor rules
	if err := runPF("pfctl", "-a", edrAnchorName, "-F", "all"); err != nil {
		return fmt.Errorf("flush pf anchor: %w", err)
	}

	// Disable pf if it was disabled before isolation
	if !m.prevPFState {
		_ = runPF("pfctl", "-d")
	}

	// Clean up temp files
	_ = os.Remove(pfConfPath)
	_ = os.Remove("/tmp/edr_main_anchor.conf")

	m.isolated = false
	return nil
}

func (m *PFIsolationManager) IsIsolated() bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.isolated
}

func buildPFConfig(allowedIPs []string) string {
	var sb strings.Builder

	sb.WriteString("# EDR Isolation Rules\n")
	sb.WriteString("# Generated by EDR Agent - DO NOT EDIT MANUALLY\n\n")

	// Pass loopback
	sb.WriteString("pass quick on lo0 all\n")

	// Pass DNS
	sb.WriteString("pass out quick proto {tcp, udp} to any port 53\n")

	// Pass established connections
	sb.WriteString("pass quick proto tcp from any to any flags S/SA keep state\n")

	// Pass EDR server IPs
	for _, ip := range allowedIPs {
		if ip == "" {
			continue
		}
		sb.WriteString(fmt.Sprintf("pass quick from any to %s\n", ip))
		sb.WriteString(fmt.Sprintf("pass quick from %s to any\n", ip))
	}

	// Block everything else
	sb.WriteString("block all\n")

	return sb.String()
}

func isPFEnabled() bool {
	out, err := exec.Command("pfctl", "-s", "info").Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "Status: Enabled")
}

func runPF(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %v: %w (output: %s)", name, args, err, string(out))
	}
	return nil
}

// ─── macOS Process Manager ────────────────────────────────────

type DarwinProcessManager struct{}

func NewDarwinProcessManager() *DarwinProcessManager {
	return &DarwinProcessManager{}
}

func (m *DarwinProcessManager) Kill(pid uint32) error {
	out, err := exec.Command("kill", "-9", fmt.Sprintf("%d", pid)).CombinedOutput()
	if err != nil {
		return fmt.Errorf("kill %d: %w (output: %s)", pid, err, string(out))
	}
	return nil
}

// ─── macOS File Quarantine ────────────────────────────────────

type DarwinFileQuarantine struct {
	quarantineDir string
	mu            sync.Mutex
	index         map[string]*collector.QuarantinedFile
}

func NewDarwinFileQuarantine(dir string) *DarwinFileQuarantine {
	return &DarwinFileQuarantine{
		quarantineDir: dir,
		index:         make(map[string]*collector.QuarantinedFile),
	}
}

func (q *DarwinFileQuarantine) Quarantine(path string) (string, error) {
	q.mu.Lock()
	defer q.mu.Unlock()

	id := generateDarwinID()
	destPath := fmt.Sprintf("%s/%s.quarantine", q.quarantineDir, id)

	// Move file
	if err := runPF("mv", path, destPath); err != nil {
		return "", fmt.Errorf("move to quarantine: %w", err)
	}

	// Strip execute bit and immutable flag
	_ = runPF("chmod", "000", destPath)
	// Add macOS quarantine extended attribute
	_ = runPF("xattr", "-w", "com.apple.quarantine",
		"0083;00000000;EDR-Agent;", destPath)

	q.index[id] = &collector.QuarantinedFile{
		ID:           id,
		OriginalPath: path,
	}

	return id, nil
}

func (q *DarwinFileQuarantine) Restore(quarantineID string, restorePath string) error {
	q.mu.Lock()
	defer q.mu.Unlock()

	entry, ok := q.index[quarantineID]
	if !ok {
		return fmt.Errorf("quarantine ID %s not found", quarantineID)
	}

	srcPath := fmt.Sprintf("%s/%s.quarantine", q.quarantineDir, quarantineID)
	dest := restorePath
	if dest == "" {
		dest = entry.OriginalPath
	}

	_ = runPF("chmod", "644", srcPath)
	_ = runPF("xattr", "-d", "com.apple.quarantine", srcPath)

	if err := runPF("mv", srcPath, dest); err != nil {
		return fmt.Errorf("restore file: %w", err)
	}

	delete(q.index, quarantineID)
	return nil
}

func (q *DarwinFileQuarantine) List() ([]collector.QuarantinedFile, error) {
	q.mu.Lock()
	defer q.mu.Unlock()

	result := make([]collector.QuarantinedFile, 0, len(q.index))
	for _, f := range q.index {
		result = append(result, *f)
	}
	return result, nil
}

func generateDarwinID() string {
	out, err := exec.Command("uuidgen").Output()
	if err != nil {
		return fmt.Sprintf("%d", 0)
	}
	return strings.TrimSpace(strings.ToLower(string(out)))
}
