apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edr-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - nats.yaml
  - server-api.yaml
  - server-ingest.yaml
  - server-detect.yaml
  - frontend.yaml
  - ingress.yaml
