//go:build linux && ebpf

package linux

// This file contains the eBPF loader for the process monitor.
// Build with: go build -tags ebpf ./...
//
// Prerequisites:
//   - cilium/ebpf: go get github.com/cilium/ebpf
//   - Compiled eBPF objects in ebpf/ directory
//   - Linux kernel >= 5.8 (for ring buffer support)
//
// NOTE: the .bpf.c sources live in agent/ebpf/ (= ../../../ebpf from this file).
// A vmlinux.h must be generated next to them first:
//   bpftool btf dump file /sys/kernel/btf/vmlinux format c > agent/ebpf/vmlinux.h
// -D__TARGET_ARCH_x86 is required so bpf_tracing.h's PT_REGS_* macros resolve.
// Only ProcessMonitor is consumed by the loader below.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags ebpf -cc clang -cflags "-O2 -g -target bpf -D__TARGET_ARCH_x86" ProcessMonitor ../../../ebpf/process_monitor.bpf.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags ebpf -cc clang -cflags "-O2 -g -target bpf -D__TARGET_ARCH_x86" NetworkMonitor ../../../ebpf/network_monitor.bpf.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags ebpf -cc clang -cflags "-O2 -g -target bpf -D__TARGET_ARCH_x86" FileMonitor ../../../ebpf/file_monitor.bpf.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags ebpf -cc clang -cflags "-O2 -g -target bpf -D__TARGET_ARCH_x86" LibraryMonitor ../../../ebpf/library_monitor.bpf.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags ebpf -cc clang -cflags "-O2 -g -target bpf -D__TARGET_ARCH_x86" TLSMonitor ../../../ebpf/tls_monitor.bpf.c

import (
	"context"
	"encoding/binary"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/edr-platform/agent/internal/collector"
	"github.com/google/uuid"
)

// ebpfProcessEventFull mirrors the C struct process_event in process_monitor.bpf.c
// Field order and sizes must match the C layout exactly (the struct is naturally
// aligned, so there is no interior padding): args_len follows args[512].
type ebpfProcessEventFull struct {
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Action      uint32 // 1=exec, 2=exit, 3=fork
	ExitCode    int32
	Comm        [16]byte
	Filename    [256]byte
	Args        [512]byte
	ArgsLen     uint32 // valid bytes in Args (NUL-separated argv); 0 if none
}

// LoadAndRunEBPFProcessMonitor loads the compiled eBPF program and streams
// process events to the output channel.
// This replaces pollProcFS when kernel >= 5.8 and eBPF is available.
func LoadAndRunEBPFProcessMonitor(ctx context.Context, out chan<- collector.ProcessEvent) error {
	// Remove memory lock limit (required for eBPF on older kernels)
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	// Load pre-compiled eBPF program (generated by bpf2go from process_monitor.bpf.c)
	objs := &ProcessMonitorObjects{}
	if err := LoadProcessMonitorObjects(objs, nil); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}
	defer objs.Close()

	// Attach to sched_process_exec tracepoint
	tpExec, err := link.Tracepoint("sched", "sched_process_exec",
		objs.HandleExec, nil)
	if err != nil {
		return fmt.Errorf("attach exec tracepoint: %w", err)
	}
	defer tpExec.Close()

	// Attach to sched_process_exit tracepoint
	tpExit, err := link.Tracepoint("sched", "sched_process_exit",
		objs.HandleExit, nil)
	if err != nil {
		return fmt.Errorf("attach exit tracepoint: %w", err)
	}
	defer tpExit.Close()

	// Open ring buffer reader
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return fmt.Errorf("open ring buffer: %w", err)
	}
	defer rd.Close()

	go func() {
		<-ctx.Done()
		rd.Close()
	}()

	// Surface silent ring-buffer record discards (size/parse mismatches) so a
	// telemetry-loss regression can't hide the way the args_len .o mismatch did.
	go reportProcessDropStats(ctx, 60*time.Second)

	// The ring buffer record holds the C struct packed (no Go-side trailing
	// padding), so the threshold for a usable record is binary.Size, not
	// unsafe.Sizeof — the latter includes Go alignment padding and would wrongly
	// reject records whose on-wire length is the packed size.
	needBytes := binary.Size(ebpfProcessEventFull{})

	// Read events from ring buffer
	for {
		record, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil {
				return nil // context cancelled
			}
			continue
		}

		if len(record.RawSample) < needBytes {
			// Undersized record = a struct size/layout mismatch (the args_len
			// stale-.o class of regression). Count it so the loss is observable.
			procRecordsDiscarded.Add(1)
			continue
		}

		var raw ebpfProcessEventFull
		if err := binary.Read(
			unsafeReader(record.RawSample),
			binary.NativeEndian, &raw); err != nil {
			procRecordsParseErr.Add(1)
			continue
		}

		action := "create"
		if raw.Action == 2 {
			action = "terminate"
		}

		comm := nullTerminated(raw.Comm[:])

		// Drop container-runtime scaffolding (runc/crun/containerd-shim/conmon) at
		// the source. The kernel captures comm on both exec and exit, so this
		// filters the create+terminate churn a busy container host generates
		// without touching the actual in-container workload processes.
		if isRuntimeNoiseProc(comm) {
			procNoiseFiltered.Add(1)
			continue
		}

		filename := nullTerminated(raw.Filename[:])
		if filename == "" {
			filename = comm
		}

		evt := collector.ProcessEvent{
			ID: uuid.New().String(),
			// raw.TimestampNs is bpf_ktime_get_ns() — nanoseconds since BOOT, not
			// since the Unix epoch. Interpreting it as epoch-ns yields a 1970-era
			// timestamp, which makes the event invisible to time-windowed event
			// queries and to detection-engine correlation windows. Use wall-clock
			// receive time instead (events are processed within ms of the exec).
			Timestamp:   time.Now(),
			PID:         raw.Pid,
			PPID:        raw.Ppid,
			ProcessName: comm,
			CommandLine: argvToCmdline(raw.Args[:], raw.ArgsLen),
			ImagePath:   filename,
			Username:    uidToUsername(raw.Uid),
			Action:      action,
		}

		// argv is now captured in-kernel at exec time (process_monitor.bpf.c), so
		// the command line is populated even for ultra short-lived processes. Only
		// fall back to a /proc read when the in-kernel capture came back empty
		// (e.g. arg_start/arg_end unavailable) and the process is still alive.
		if action == "create" {
			if evt.CommandLine == "" {
				evt.CommandLine = readProcCmdline(raw.Pid, comm)
			}
			// Runc's container-init re-exec has comm "6" (so isRuntimeNoiseProc
			// misses it) but command line "runc init" — drop it here once the cmd
			// line is known.
			if isRuntimeNoiseCmd(evt.CommandLine) {
				procNoiseFiltered.Add(1)
				continue
			}
			// Dynamic-linker injection env vars (LD_PRELOAD etc.) for T1574.006.
			evt.EnvVars = readProcSuspiciousEnv(raw.Pid)
		}

		select {
		case out <- evt:
		case <-ctx.Done():
			return nil
		}
	}
}

func nullTerminated(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

// argvToCmdline renders the in-kernel argv capture (the first n bytes of b, a run
// of NUL-separated arguments) as a single space-joined command line, matching the
// format the polling collector produces from /proc/<pid>/cmdline. Returns "" when
// no argv was captured (n == 0).
func argvToCmdline(b []byte, n uint32) string {
	if n == 0 {
		return ""
	}
	if int(n) > len(b) {
		n = uint32(len(b))
	}
	out := make([]byte, 0, n)
	for _, c := range b[:n] {
		if c == 0 {
			c = ' '
		}
		out = append(out, c)
	}
	for len(out) > 0 && out[len(out)-1] == ' ' {
		out = out[:len(out)-1]
	}
	if hasCorruptBytes(string(out)) {
		return ""
	}
	return string(out)
}

// readProcCmdline returns the full command line of a live process from
// /proc/<pid>/cmdline, where arguments are separated by NUL bytes. Returns ""
// if the process already exited or the file is unreadable.
//
// wantComm is the exec-time comm (bpf_get_current_comm) of the process this
// fallback is enriching. It guards against PID reuse: an ultra short-lived
// process can exit and have its PID recycled by an unrelated process before this
// userspace fallback runs — rampant under container/runc churn — which would
// otherwise splice that unrelated process's command line onto this exec event
// (observed: `image=wget` paired with a `runc … exec` command line). When
// /proc/<pid>/comm no longer matches wantComm the PID was reused, so we return ""
// rather than a mispaired command line. A read failure means the process is gone
// (also unsafe to trust), so it likewise returns "".
func readProcCmdline(pid uint32, wantComm string) string {
	if wantComm != "" {
		commData, err := os.ReadFile(fmt.Sprintf("/proc/%d/comm", pid))
		if err != nil || strings.TrimRight(string(commData), "\n") != wantComm {
			return ""
		}
	}
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/cmdline", pid))
	if err != nil || len(data) == 0 {
		return ""
	}
	out := make([]byte, 0, len(data))
	for _, b := range data {
		if b == 0 {
			b = ' '
		}
		out = append(out, b)
	}
	for len(out) > 0 && out[len(out)-1] == ' ' {
		out = out[:len(out)-1]
	}
	if hasCorruptBytes(string(out)) {
		return "" // binary bootstrap argv (e.g. runc nsexec), not a command line
	}
	return string(out)
}

type byteReader struct {
	data []byte
	pos  int
}

func unsafeReader(data []byte) *byteReader { return &byteReader{data: data} }

func (r *byteReader) Read(p []byte) (int, error) {
	n := copy(p, r.data[r.pos:])
	r.pos += n
	if n == 0 {
		return 0, fmt.Errorf("EOF")
	}
	return n, nil
}

func uidToUsername(uid uint32) string {
	// Read from /etc/passwd
	data, err := os.ReadFile("/etc/passwd")
	if err != nil {
		return fmt.Sprintf("uid:%d", uid)
	}
	// Parse entries: name:x:uid:...
	for _, line := range splitLines(string(data)) {
		fields := splitColon(line)
		if len(fields) >= 3 && fields[2] == fmt.Sprintf("%d", uid) {
			return fields[0]
		}
	}
	return fmt.Sprintf("uid:%d", uid)
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i, c := range s {
		if c == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	return lines
}

func splitColon(s string) []string {
	var parts []string
	start := 0
	for i, c := range s {
		if c == ':' {
			parts = append(parts, s[start:i])
			start = i + 1
		}
	}
	parts = append(parts, s[start:])
	return parts
}
