// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && ebpf

package linux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FileMonitorOpenatArgs struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Uid         uint32
	Path        [256]int8
	Flags       int32
	Mode        int32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FileMonitorMapFileEvents         = "file_events"
	FileMonitorMapOpenatMap          = "openat_map"
	FileMonitorProgHandleOpenatEnter = "handle_openat_enter"
	FileMonitorProgHandleOpenatExit  = "handle_openat_exit"
	FileMonitorProgHandleVfsRename   = "handle_vfs_rename"
	FileMonitorProgHandleVfsUnlink   = "handle_vfs_unlink"
)

// LoadFileMonitor returns the embedded CollectionSpec for FileMonitor.
func LoadFileMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FileMonitor: %w", err)
	}

	return spec, err
}

// LoadFileMonitorObjects loads FileMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileMonitorObjects
//	*FileMonitorPrograms
//	*FileMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFileMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorSpecs struct {
	FileMonitorProgramSpecs
	FileMonitorMapSpecs
	FileMonitorVariableSpecs
}

// FileMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorProgramSpecs struct {
	HandleOpenatEnter *ebpf.ProgramSpec `ebpf:"handle_openat_enter"`
	HandleOpenatExit  *ebpf.ProgramSpec `ebpf:"handle_openat_exit"`
	HandleVfsRename   *ebpf.ProgramSpec `ebpf:"handle_vfs_rename"`
	HandleVfsUnlink   *ebpf.ProgramSpec `ebpf:"handle_vfs_unlink"`
}

// FileMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorMapSpecs struct {
	FileEvents *ebpf.MapSpec `ebpf:"file_events"`
	OpenatMap  *ebpf.MapSpec `ebpf:"openat_map"`
}

// FileMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorVariableSpecs struct {
}

// FileMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorObjects struct {
	FileMonitorPrograms
	FileMonitorMaps
	FileMonitorVariables
}

func (o *FileMonitorObjects) Close() error {
	return _FileMonitorClose(
		&o.FileMonitorPrograms,
		&o.FileMonitorMaps,
	)
}

// FileMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorMaps struct {
	FileEvents *ebpf.Map `ebpf:"file_events"`
	OpenatMap  *ebpf.Map `ebpf:"openat_map"`
}

func (m *FileMonitorMaps) Close() error {
	return _FileMonitorClose(
		m.FileEvents,
		m.OpenatMap,
	)
}

// FileMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorVariables struct {
}

// FileMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorPrograms struct {
	HandleOpenatEnter *ebpf.Program `ebpf:"handle_openat_enter"`
	HandleOpenatExit  *ebpf.Program `ebpf:"handle_openat_exit"`
	HandleVfsRename   *ebpf.Program `ebpf:"handle_vfs_rename"`
	HandleVfsUnlink   *ebpf.Program `ebpf:"handle_vfs_unlink"`
}

func (p *FileMonitorPrograms) Close() error {
	return _FileMonitorClose(
		p.HandleOpenatEnter,
		p.HandleOpenatExit,
		p.HandleVfsRename,
		p.HandleVfsUnlink,
	)
}

func _FileMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filemonitor_bpfel.o
var _FileMonitorBytes []byte
