// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && ebpf

package linux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FilelessMonitorMapFilelessEvents  = "fileless_events"
	FilelessMonitorProgHandleExecveat = "handle_execveat"
	FilelessMonitorProgHandleMemfd    = "handle_memfd"
)

// LoadFilelessMonitor returns the embedded CollectionSpec for FilelessMonitor.
func LoadFilelessMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilelessMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FilelessMonitor: %w", err)
	}

	return spec, err
}

// LoadFilelessMonitorObjects loads FilelessMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FilelessMonitorObjects
//	*FilelessMonitorPrograms
//	*FilelessMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFilelessMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFilelessMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FilelessMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilelessMonitorSpecs struct {
	FilelessMonitorProgramSpecs
	FilelessMonitorMapSpecs
	FilelessMonitorVariableSpecs
}

// FilelessMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilelessMonitorProgramSpecs struct {
	HandleExecveat *ebpf.ProgramSpec `ebpf:"handle_execveat"`
	HandleMemfd    *ebpf.ProgramSpec `ebpf:"handle_memfd"`
}

// FilelessMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilelessMonitorMapSpecs struct {
	FilelessEvents *ebpf.MapSpec `ebpf:"fileless_events"`
}

// FilelessMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilelessMonitorVariableSpecs struct {
}

// FilelessMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFilelessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilelessMonitorObjects struct {
	FilelessMonitorPrograms
	FilelessMonitorMaps
	FilelessMonitorVariables
}

func (o *FilelessMonitorObjects) Close() error {
	return _FilelessMonitorClose(
		&o.FilelessMonitorPrograms,
		&o.FilelessMonitorMaps,
	)
}

// FilelessMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFilelessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilelessMonitorMaps struct {
	FilelessEvents *ebpf.Map `ebpf:"fileless_events"`
}

func (m *FilelessMonitorMaps) Close() error {
	return _FilelessMonitorClose(
		m.FilelessEvents,
	)
}

// FilelessMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFilelessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilelessMonitorVariables struct {
}

// FilelessMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFilelessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilelessMonitorPrograms struct {
	HandleExecveat *ebpf.Program `ebpf:"handle_execveat"`
	HandleMemfd    *ebpf.Program `ebpf:"handle_memfd"`
}

func (p *FilelessMonitorPrograms) Close() error {
	return _FilelessMonitorClose(
		p.HandleExecveat,
		p.HandleMemfd,
	)
}

func _FilelessMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filelessmonitor_bpfeb.o
var _FilelessMonitorBytes []byte
