// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && ebpf

package linux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	LibraryMonitorMapLibEvents     = "lib_events"
	LibraryMonitorProgHandleDlopen = "handle_dlopen"
)

// LoadLibraryMonitor returns the embedded CollectionSpec for LibraryMonitor.
func LoadLibraryMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LibraryMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load LibraryMonitor: %w", err)
	}

	return spec, err
}

// LoadLibraryMonitorObjects loads LibraryMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*LibraryMonitorObjects
//	*LibraryMonitorPrograms
//	*LibraryMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadLibraryMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadLibraryMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// LibraryMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LibraryMonitorSpecs struct {
	LibraryMonitorProgramSpecs
	LibraryMonitorMapSpecs
	LibraryMonitorVariableSpecs
}

// LibraryMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LibraryMonitorProgramSpecs struct {
	HandleDlopen *ebpf.ProgramSpec `ebpf:"handle_dlopen"`
}

// LibraryMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LibraryMonitorMapSpecs struct {
	LibEvents *ebpf.MapSpec `ebpf:"lib_events"`
}

// LibraryMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LibraryMonitorVariableSpecs struct {
}

// LibraryMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadLibraryMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type LibraryMonitorObjects struct {
	LibraryMonitorPrograms
	LibraryMonitorMaps
	LibraryMonitorVariables
}

func (o *LibraryMonitorObjects) Close() error {
	return _LibraryMonitorClose(
		&o.LibraryMonitorPrograms,
		&o.LibraryMonitorMaps,
	)
}

// LibraryMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadLibraryMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type LibraryMonitorMaps struct {
	LibEvents *ebpf.Map `ebpf:"lib_events"`
}

func (m *LibraryMonitorMaps) Close() error {
	return _LibraryMonitorClose(
		m.LibEvents,
	)
}

// LibraryMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadLibraryMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type LibraryMonitorVariables struct {
}

// LibraryMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadLibraryMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type LibraryMonitorPrograms struct {
	HandleDlopen *ebpf.Program `ebpf:"handle_dlopen"`
}

func (p *LibraryMonitorPrograms) Close() error {
	return _LibraryMonitorClose(
		p.HandleDlopen,
	)
}

func _LibraryMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed librarymonitor_bpfel.o
var _LibraryMonitorBytes []byte
