// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && ebpf

package linux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ProcessMonitorProcessEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Action      uint32
	ExitCode    int32
	Comm        [16]int8
	Filename    [256]int8
	Args        [512]int8
	ArgsLen     uint32
	_           [4]byte
}

// LoadProcessMonitor returns the embedded CollectionSpec for ProcessMonitor.
func LoadProcessMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ProcessMonitor: %w", err)
	}

	return spec, err
}

// LoadProcessMonitorObjects loads ProcessMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessMonitorObjects
//	*ProcessMonitorPrograms
//	*ProcessMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcessMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMonitorSpecs struct {
	ProcessMonitorProgramSpecs
	ProcessMonitorMapSpecs
	ProcessMonitorVariableSpecs
}

// ProcessMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMonitorProgramSpecs struct {
	HandleExec *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
}

// ProcessMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMonitorMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	ExecveMap *ebpf.MapSpec `ebpf:"execve_map"`
	Heap      *ebpf.MapSpec `ebpf:"heap"`
}

// ProcessMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMonitorVariableSpecs struct {
}

// ProcessMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMonitorObjects struct {
	ProcessMonitorPrograms
	ProcessMonitorMaps
	ProcessMonitorVariables
}

func (o *ProcessMonitorObjects) Close() error {
	return _ProcessMonitorClose(
		&o.ProcessMonitorPrograms,
		&o.ProcessMonitorMaps,
	)
}

// ProcessMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMonitorMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	ExecveMap *ebpf.Map `ebpf:"execve_map"`
	Heap      *ebpf.Map `ebpf:"heap"`
}

func (m *ProcessMonitorMaps) Close() error {
	return _ProcessMonitorClose(
		m.Events,
		m.ExecveMap,
		m.Heap,
	)
}

// ProcessMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMonitorVariables struct {
}

// ProcessMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMonitorPrograms struct {
	HandleExec *ebpf.Program `ebpf:"handle_exec"`
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
}

func (p *ProcessMonitorPrograms) Close() error {
	return _ProcessMonitorClose(
		p.HandleExec,
		p.HandleExit,
	)
}

func _ProcessMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processmonitor_bpfeb.o
var _ProcessMonitorBytes []byte
