package main

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// configTemplate is the agent.toml a fresh install starts from. It mirrors what
// deploy/install/install.sh writes, so a host configured by the package and one
// configured by the script are indistinguishable afterwards.
const configTemplate = `# Kizashi Agent Configuration
# Generated by edr-agent -write-config
# Do not edit manually — changes may be overwritten by policy sync.

[agent]
id       = "%s"
hostname = "%s"

[server]
url                  = "%s"
grpc_port            = 9090
ingestion_grpc_port  = 9091
connect_timeout_sec  = 30
# cert_pins = []  # Optional: SHA-256 SPKI pins for certificate pinning

[collection]
process_monitoring = true
network_monitoring = true
file_monitoring    = true

[logging]
level = "info"
`

// runWriteConfig implements `edr-agent -write-config -server <url>`, used by the
// OS packages (MSI custom action, .deb/.rpm postinstall, macOS pkg postinstall)
// to produce a first-run agent.toml.
//
// It exists because a package cannot know the server URL or the agent identity
// at build time, and because each platform's packaging language is a bad place
// to generate a UUID and write TOML — the MSI would need a bundled script, the
// pkg a second interpreter, and all three would drift from each other. One
// implementation in the binary keeps them identical.
//
// It REFUSES to overwrite an existing config. That is the whole safety property:
// on upgrade, agent.toml already holds this endpoint's agent ID, and generating
// a new one would re-enrol the host under a fresh identity, orphaning every
// alert, incident and timeline entry attached to the old one. Packages call this
// unconditionally, so "already configured" must be a no-op, not a reset.
func runWriteConfig(configPath, serverURL string) int {
	if _, err := os.Stat(configPath); err == nil {
		fmt.Fprintf(os.Stderr, "設定ファイルが既に存在するため何もしません: %s\n", configPath)
		return 0
	} else if !os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "設定ファイルを確認できません: %v\n", err)
		return 1
	}

	serverURL = strings.TrimRight(strings.TrimSpace(serverURL), "/")
	if serverURL == "" {
		fmt.Fprintln(os.Stderr, "-server が指定されていないため設定ファイルを作成しません。")
		fmt.Fprintln(os.Stderr, "サーバURLの無い設定は、起動はするがどこにも接続しないエージェントを生みます。")
		return 1
	}

	agentID, err := newUUIDv4()
	if err != nil {
		fmt.Fprintf(os.Stderr, "エージェントIDを生成できません: %v\n", err)
		return 1
	}
	host, err := os.Hostname()
	if err != nil || host == "" {
		host = "unknown"
	}

	if err := os.MkdirAll(filepath.Dir(configPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "設定ディレクトリを作成できません: %v\n", err)
		return 1
	}

	body := fmt.Sprintf(configTemplate, agentID, host, serverURL)

	// 0640, and written with O_EXCL so two packages racing (an MSI repair
	// alongside a scheduled install, say) cannot both decide the file was
	// missing and write two different agent IDs.
	f, err := os.OpenFile(configPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o640)
	if err != nil {
		if os.IsExist(err) {
			fmt.Fprintf(os.Stderr, "設定ファイルが同時に作成されたため何もしません: %s\n", configPath)
			return 0
		}
		fmt.Fprintf(os.Stderr, "設定ファイルを作成できません: %v\n", err)
		return 1
	}
	defer f.Close()

	if _, err := f.WriteString(body); err != nil {
		fmt.Fprintf(os.Stderr, "設定ファイルを書き込めません: %v\n", err)
		return 1
	}

	fmt.Fprintf(os.Stderr, "設定ファイルを作成しました: %s (agent id %s)\n", configPath, agentID)
	return 0
}

// newUUIDv4 returns a random RFC 4122 version 4 UUID.
//
// Hand-rolled rather than pulling google/uuid into this path: the package is
// already an import of the agent, but this runs in a mode where the fewer
// moving parts between "package installed" and "config written" the better, and
// the formatting is four lines.
func newUUIDv4() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}
