apiVersion: v1
kind: Service
metadata:
  name: {{ include "edr-platform.fullname" . }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edr-platform.nats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "edr-platform.nats.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ .Values.nats.port }}
      targetPort: client
      protocol: TCP
    - name: monitoring
      port: {{ .Values.nats.monitoringPort }}
      targetPort: monitoring
      protocol: TCP
