apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edr-platform.fullname" . }}-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edr-platform.server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote }}
  CLAUDE_API_KEY: {{ .Values.secrets.claudeApiKey | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
