apiVersion: v1
kind: Service
metadata:
  name: {{ include "kizashi.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kizashi.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "kizashi.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.httpPort }}
      targetPort: http
      protocol: TCP
