package rulepack

import (
	"os"
	"path/filepath"
	"testing"
)

// The packs this repository ships must load.
//
// A pack is content, and content is edited by hand and regenerated by tooling.
// Either can produce a file that parses as JSON and is still unusable — a
// misspelled field, an empty rule body, two rules sharing a name. None of those
// announce themselves: the pack loads fewer rules than it lists, or loads rules
// that can never match, and the shortfall shows up months later as detections
// that never fired.
//
// Skipped when the directory is absent. The open source edition ships no packs
// and must not fail its test suite over content it does not carry.
func TestShippedPacksAreLoadable(t *testing.T) {
	dir := filepath.Join("..", "..", "..", "rulepacks")
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) == 0 {
		t.Skip("no rulepacks/ in this edition")
	}

	for _, path := range paths {
		t.Run(filepath.Base(path), func(t *testing.T) {
			f, err := os.Open(path) //nolint:gosec // repo-relative path from Glob
			if err != nil {
				t.Fatal(err)
			}
			defer func() { _ = f.Close() }()

			pack, err := Parse(f)
			if err != nil {
				t.Fatalf("shipped pack does not load: %v", err)
			}
			if len(pack.Rules) == 0 {
				t.Fatal("shipped pack has no rules")
			}

			// Every rule must be reachable through a distinct pack_key, or the
			// load silently applies fewer rules than the file describes.
			keys := map[string]bool{}
			for _, r := range pack.Rules {
				key := pack.PackKey(r.Name)
				if keys[key] {
					t.Errorf("duplicate pack_key %q", key)
				}
				keys[key] = true
			}
			t.Logf("%s: %d rules (pack %q version %q)",
				filepath.Base(path), len(pack.Rules), pack.Name, pack.Version)
		})
	}
}
