apiVersion: v1
kind: Service
metadata:
  name: {{ include "kizashi.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kizashi.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "kizashi.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.api.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
