apiVersion: v1
kind: Service
metadata:
  name: {{ include "kizashi.fullname" . }}-detection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kizashi.componentLabels" (dict "root" . "component" "detection") | nindent 4 }}
  {{- with .Values.detection.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.detection.service.type }}
  selector:
    {{- include "kizashi.componentSelectorLabels" (dict "root" . "component" "detection") | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.detection.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
