package handlers

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
)

// InstallerHandler serves agent installer scripts and binary downloads.
type InstallerHandler struct {
	serverURL string
	binDir    string // directory containing edr-agent-* binaries (AGENT_BIN_DIR)
	pool      *pgxpool.Pool
}

// NewInstallerHandler creates a new InstallerHandler.
func NewInstallerHandler(serverURL, binDir string, pool ...*pgxpool.Pool) *InstallerHandler {
	h := &InstallerHandler{serverURL: serverURL, binDir: binDir}
	if len(pool) > 0 {
		h.pool = pool[0]
	}
	return h
}

// installerToken is the DB/JSON shape for installer_tokens rows.
type installerToken struct {
	ID        string     `json:"id"`
	Label     *string    `json:"label"`
	CreatedAt time.Time  `json:"created_at"`
	UsedAt    *time.Time `json:"used_at"`
	AgentName *string    `json:"agent_name"`
	Revoked   bool       `json:"revoked"`
}

// ListTokens handles GET /api/v1/admin/installer/tokens
func (h *InstallerHandler) ListTokens(c *gin.Context) {
	if h.pool == nil {
		c.JSON(http.StatusOK, gin.H{"tokens": []interface{}{}})
		return
	}
	rows, err := h.pool.Query(c.Request.Context(), `
		SELECT t.id, t.label, t.created_at, t.used_at, a.hostname, t.revoked
		FROM installer_tokens t
		LEFT JOIN agents a ON a.id = t.agent_id
		WHERE t.revoked = false
		ORDER BY t.created_at DESC`)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": dbErrMsg(err)})
		return
	}
	defer rows.Close()

	var tokens []installerToken
	for rows.Next() {
		var tk installerToken
		if scanErr := rows.Scan(&tk.ID, &tk.Label, &tk.CreatedAt, &tk.UsedAt, &tk.AgentName, &tk.Revoked); scanErr == nil {
			tokens = append(tokens, tk)
		}
	}
	if err := rows.Err(); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": dbErrMsg(err)})
		return
	}
	if tokens == nil {
		tokens = []installerToken{}
	}
	c.JSON(http.StatusOK, gin.H{"tokens": tokens})
}

// CreateToken handles POST /api/v1/admin/installer/tokens
func (h *InstallerHandler) CreateToken(c *gin.Context) {
	var req struct {
		Label string `json:"label"`
	}
	_ = c.ShouldBindJSON(&req)

	// Generate 32 random hex chars
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "トークン生成に失敗しました"})
		return
	}
	tokenID := hex.EncodeToString(b)
	now := time.Now().UTC()

	var labelPtr *string
	if req.Label != "" {
		labelPtr = &req.Label
	}

	userID, _ := c.Get("user_id")
	userIDStr, _ := userID.(string)

	if h.pool != nil {
		_, err := h.pool.Exec(c.Request.Context(),
			`INSERT INTO installer_tokens (id, label, created_by, created_at, revoked)
			 VALUES ($1, $2, $3::uuid, $4, false)`,
			tokenID, labelPtr, nilIfEmpty(userIDStr), now)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": dbErrMsg(err)})
			return
		}
	}

	c.JSON(http.StatusCreated, installerToken{
		ID:        tokenID,
		Label:     labelPtr,
		CreatedAt: now,
		Revoked:   false,
	})
}

// RevokeToken handles DELETE /api/v1/admin/installer/tokens/:id
func (h *InstallerHandler) RevokeToken(c *gin.Context) {
	id := c.Param("id")
	if h.pool != nil {
		ct, err := h.pool.Exec(c.Request.Context(),
			`UPDATE installer_tokens SET revoked = true WHERE id = $1 AND revoked = false`, id)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": dbErrMsg(err)})
			return
		}
		if ct.RowsAffected() == 0 {
			c.JSON(http.StatusNotFound, gin.H{"error": "トークンが見つかりません"})
			return
		}
	}
	c.JSON(http.StatusOK, gin.H{"status": "revoked"})
}

// LinuxInstaller handles GET /api/v1/installer/linux/:arch
// Returns a bash install script.
func (h *InstallerHandler) LinuxInstaller(c *gin.Context) {
	arch := c.Param("arch")
	if arch != "amd64" && arch != "arm64" {
		arch = "amd64"
	}
	serverURL := h.serverURL
	token := c.Query("token")
	group := c.Query("group")
	service := c.DefaultQuery("service", "true")

	_ = group // reserved for future use
	serviceFlag := ""
	if service == "true" {
		serviceFlag = "--install-service"
	}

	script := fmt.Sprintf(`#!/bin/bash
# EDR Platform Agent Installer for Linux (%s)
# Generated by EDR Platform

set -euo pipefail

AGENT_DOWNLOAD_URL="%s/api/v1/installer/download/linux/%s"
SERVER_URL="%s"
TOKEN="%s"
SERVICE_FLAG="%s"
INSTALL_DIR="/opt/edr-agent"
BINARY_NAME="edr-agent"
CONFIG_PATH="/etc/edr-agent/config.toml"

echo "[*] EDR Platform エージェントをインストール中..."

# rootチェック
if [[ "$EUID" -ne 0 ]]; then
  echo "[!] このスクリプトは root (sudo) で実行してください"
  exit 1
fi

# バイナリダウンロード
echo "[*] エージェントバイナリをダウンロード中..."
mkdir -p "$INSTALL_DIR"
if curl -fsSL --connect-timeout 30 --retry 3 \
    "$AGENT_DOWNLOAD_URL" -o "$INSTALL_DIR/$BINARY_NAME"; then
  chmod +x "$INSTALL_DIR/$BINARY_NAME"
  echo "[+] バイナリのダウンロード完了"
else
  echo "[!] バイナリのダウンロードに失敗しました"
  exit 1
fi

# エージェント登録 (config.toml を自動生成)
echo "[*] エージェントを登録中..."
mkdir -p /etc/edr-agent
if "$INSTALL_DIR/$BINARY_NAME" --enroll \
    --server "$SERVER_URL" \
    --token "$TOKEN" \
    --config "$CONFIG_PATH"; then
  echo "[+] 登録完了"
else
  echo "[!] 登録に失敗しました。SERVER_URLとTOKENを確認してください"
  exit 1
fi

# systemdサービスのインストール
if [[ "$SERVICE_FLAG" == "--install-service" ]] && command -v systemctl &>/dev/null; then
  cat > /etc/systemd/system/edr-agent.service << EOFSVC
[Unit]
Description=EDR Platform Agent
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/$BINARY_NAME --config $CONFIG_PATH
Restart=on-failure
RestartSec=10
User=root
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOFSVC
  systemctl daemon-reload
  systemctl enable --now edr-agent
  echo "[+] サービスを有効化しました (systemctl status edr-agent で確認できます)"
fi

echo "[+] インストール完了"
`, arch, serverURL, arch, serverURL, token, serviceFlag)

	c.Header("Content-Type", "text/plain; charset=utf-8")
	c.Header("Content-Disposition", "inline; filename=install-edr-agent.sh")
	c.String(http.StatusOK, script)
}

// WindowsInstaller handles GET /api/v1/installer/windows/:arch
// Returns a PowerShell install script.
func (h *InstallerHandler) WindowsInstaller(c *gin.Context) {
	arch := c.Param("arch")
	if arch != "amd64" && arch != "arm64" {
		arch = "amd64"
	}
	serverURL := h.serverURL
	token := c.Query("token")

	// PowerShellスクリプトをGoの文字列で構築（バッククォートはPSの改行継続文字のため結合で対応）
	bq := "`" // PowerShell行継続文字
	script := "# EDR Platform Agent Installer for Windows (" + arch + ")\n" +
		"# \u7ba1\u7406\u8005\u6a29\u9650\u306e PowerShell \u3067\u5b9f\u884c\u3057\u3066\u304f\u3060\u3055\u3044\n" +
		"# \u5b9f\u884c\u65b9\u6cd5: powershell -ExecutionPolicy Bypass -File Install-EDRAgent.ps1\n\n" +
		"#Requires -RunAsAdministrator\n\n" +
		"$ErrorActionPreference = \"Stop\"\n\n" +
		"$ServerUrl   = \"" + serverURL + "\"\n" +
		"$Token       = \"" + token + "\"\n" +
		"$InstallDir  = \"C:\\Program Files\\EDR Agent\"\n" +
		"$BinaryName  = \"edr-agent.exe\"\n" +
		"$DownloadUrl = \"" + serverURL + "/api/v1/installer/download/windows/" + arch + "\"\n" +
		"$ServiceName = \"EDRAgent\"\n\n" +
		"Write-Host \"[*] EDR Platform \u30a8\u30fc\u30b8\u30a7\u30f3\u30c8\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u4e2d...\" -ForegroundColor Cyan\n\n" +
		"New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null\n\n" +
		"Write-Host \"[*] \u30a8\u30fc\u30b8\u30a7\u30f3\u30c8\u30d0\u30a4\u30ca\u30ea\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u4e2d...\"\n" +
		"$headers = @{ \"Authorization\" = \"Bearer $Token\" }\n" +
		"try {\n" +
		"    Invoke-WebRequest -Uri $DownloadUrl -Headers $headers " + bq + "\n" +
		"        -OutFile \"$InstallDir\\$BinaryName\" -UseBasicParsing\n" +
		"    Write-Host \"[+] \u30d0\u30a4\u30ca\u30ea\u306e\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u5b8c\u4e86\" -ForegroundColor Green\n" +
		"} catch {\n" +
		"    Write-Host \"[!] \u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u5931\u6557: $_\" -ForegroundColor Red; exit 1\n" +
		"}\n\n" +
		"@\"\nserver_url: $ServerUrl\ntoken: $Token\nlog_level: info\n\"@ | Set-Content \"$InstallDir\\config.yaml\" -Encoding UTF8\n\n" +
		"if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {\n" +
		"    Stop-Service -Name $ServiceName -Force\n" +
		"    sc.exe delete $ServiceName | Out-Null\n" +
		"}\n" +
		"$binPath = \"`\"$InstallDir\\$BinaryName`\" --config `\"$InstallDir\\config.yaml`\"\"\n" +
		"New-Service -Name $ServiceName -BinaryPathName $binPath " + bq + "\n" +
		"    -DisplayName \"EDR Platform Agent\" -StartupType Automatic " + bq + "\n" +
		"    -Description \"EDR Platform endpoint security agent\" | Out-Null\n" +
		"Start-Service -Name $ServiceName\n\n" +
		"Write-Host \"[+] \u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u5b8c\u4e86: $InstallDir\\$BinaryName\" -ForegroundColor Green\n" +
		"Write-Host \"[+] \u30b5\u30fc\u30d3\u30b9 '$ServiceName' \u304c\u8d77\u52d5\u3057\u307e\u3057\u305f\"\n"

	c.Header("Content-Type", "text/plain; charset=utf-8")
	c.Header("Content-Disposition", "inline; filename=Install-EDRAgent.ps1")
	c.String(http.StatusOK, script)
}

// Download handles GET /api/v1/installer/download/:os/:arch
// Serves the pre-built agent binary from h.binDir when available.
// Responds with manual installation instructions when the binary is not found.
func (h *InstallerHandler) Download(c *gin.Context) {
	osParam := c.Param("os")
	arch := c.Param("arch")

	// Validate os
	validOS := map[string]bool{"linux": true, "windows": true, "darwin": true}
	if !validOS[osParam] {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": fmt.Sprintf("無効なOSです: %s (linux|windows|darwin)", osParam),
		})
		return
	}

	// Validate arch
	validArch := map[string]bool{"amd64": true, "arm64": true, "386": true}
	if !validArch[arch] {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": fmt.Sprintf("無効なアーキテクチャです: %s (amd64|arm64|386)", arch),
		})
		return
	}

	filename := fmt.Sprintf("edr-agent-%s-%s", osParam, arch)
	if osParam == "windows" {
		filename += ".exe"
	}

	fullPath := filepath.Join(h.binDir, filename)

	// Prevent path traversal
	if !strings.HasPrefix(filepath.Clean(fullPath), filepath.Clean(h.binDir)) {
		c.JSON(http.StatusForbidden, gin.H{"error": "forbidden"})
		return
	}

	if _, err := os.Stat(fullPath); err == nil {
		c.FileAttachment(fullPath, filename)
		return
	}

	// Binary not found — return helpful instructions
	serverURL := h.serverURL
	linuxInstall := fmt.Sprintf(
		"curl -fsSL %s/api/v1/installer/linux/amd64 | sudo bash",
		serverURL,
	)
	windowsInstall := fmt.Sprintf(
		"Invoke-WebRequest -Uri '%s/api/v1/installer/windows/amd64' -OutFile Install-EDRAgent.ps1; .\\Install-EDRAgent.ps1",
		serverURL,
	)
	darwinInstall := fmt.Sprintf(
		"curl -fsSL %s/api/v1/installer/linux/amd64 | sudo bash",
		serverURL,
	)

	c.JSON(http.StatusNotFound, gin.H{
		"message": "エージェントバイナリが見つかりません",
		"note":    "AGENT_BIN_DIRにバイナリを配置するか、手動インストール手順を参照してください",
		"manual_install": gin.H{
			"linux":   linuxInstall,
			"windows": windowsInstall,
			"darwin":  darwinInstall,
		},
	})
}

// GenerateInstallScript handles GET /api/v1/installer/script and
// GET /api/v1/installer/script/:os/:arch
// os and arch can be supplied as path params OR query params (?os=linux&arch=amd64).
func (h *InstallerHandler) GenerateInstallScript(c *gin.Context) {
	osParam := c.Param("os")
	if osParam == "" {
		osParam = c.DefaultQuery("os", "linux")
	}
	arch := c.Param("arch")
	if arch == "" {
		arch = c.DefaultQuery("arch", "amd64")
	}
	token := c.Query("token")
	group := c.Query("group")

	serverURL := h.serverURL
	downloadURL := fmt.Sprintf("%s/api/v1/installer/download/%s/%s", serverURL, osParam, arch)

	switch osParam {
	case "linux", "darwin":
		groupLine := ""
		if group != "" {
			groupLine = fmt.Sprintf("group: %s", strings.ReplaceAll(group, "'", ""))
		}
		script := fmt.Sprintf(`#!/bin/bash
# EDR Platform Agent Installer for %s/%s
set -e

DOWNLOAD_URL="%s"
SERVER_URL="%s"
TOKEN="%s"
INSTALL_DIR="/opt/edr-agent"

echo "[*] エージェントバイナリをダウンロード中..."
mkdir -p "$INSTALL_DIR"
curl -fsSL "$DOWNLOAD_URL" -o "$INSTALL_DIR/edr-agent"
chmod +x "$INSTALL_DIR/edr-agent"

cat > "$INSTALL_DIR/config.yaml" <<EOF
server_url: $SERVER_URL
token: $TOKEN
%s
log_level: info
EOF

if command -v systemctl &>/dev/null; then
    cat > /etc/systemd/system/edr-agent.service <<EOF
[Unit]
Description=EDR Platform Agent
After=network.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/edr-agent --config $INSTALL_DIR/config.yaml
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now edr-agent
    echo "[+] サービスを開始しました"
fi

echo "[+] インストール完了"
`, osParam, arch, downloadURL, serverURL, token, groupLine)

		c.Header("Content-Type", "text/plain; charset=utf-8")
		c.Header("Content-Disposition", "inline; filename=install-edr-agent.sh")
		c.String(http.StatusOK, script)

	case "windows":
		// Build the PowerShell script with regular string concatenation to avoid
		// backtick conflicts inside Go raw string literals.
		bq := "`"
		script := "# EDR Platform Agent Installer for Windows/" + arch + "\n" +
			"# Run as Administrator in PowerShell\n\n" +
			"$ServerUrl   = \"" + serverURL + "\"\n" +
			"$Token       = \"" + token + "\"\n" +
			"$DownloadUrl = \"" + downloadURL + "\"\n" +
			"$InstallDir  = \"C:\\Program Files\\EDR Agent\"\n" +
			"$ConfigFile  = \"$InstallDir\\config.toml\"\n" +
			"$SvcName     = \"EDRAgent\"\n\n" +
			"Write-Host \"[*] EDR Platform エージェントをインストール中...\" -ForegroundColor Cyan\n" +
			"New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null\n" +
			"New-Item -ItemType Directory -Force -Path 'C:\\ProgramData\\EDRAgent\\quarantine' | Out-Null\n\n" +
			"Write-Host \"[*] エージェントバイナリをダウンロード中...\"\n" +
			"$headers = @{ \"Authorization\" = \"Bearer $Token\" }\n" +
			"try {\n" +
			"    Invoke-WebRequest -Uri $DownloadUrl -Headers $headers " + bq + "\n" +
			"        -OutFile \"$InstallDir\\edr-agent.exe\" -UseBasicParsing\n" +
			"    Write-Host \"[+] バイナリのダウンロード完了\" -ForegroundColor Green\n" +
			"} catch {\n" +
			"    Write-Host \"[!] ダウンロード失敗: $_\" -ForegroundColor Red; exit 1\n" +
			"}\n\n" +
			"$AgentID = [System.Guid]::NewGuid().ToString()\n" +
			"$Hostname = $env:COMPUTERNAME\n" +
			"@\"\n" +
			"[agent]\n" +
			"id = \"$AgentID\"\n" +
			"hostname = \"$Hostname\"\n\n" +
			"[server]\n" +
			"url = \"$ServerUrl\"\n" +
			"grpc_port = 9090\n" +
			"ingestion_grpc_port = 9091\n" +
			"connect_timeout_sec = 30\n\n" +
			"[collection]\n" +
			"process_monitoring = true\n" +
			"file_monitoring = true\n" +
			"network_monitoring = true\n" +
			"dns_monitoring = true\n" +
			"event_batch_interval_ms = 500\n" +
			"local_buffer_size_mb = 100\n" +
			"max_events_per_second = 1000\n\n" +
			"[response]\n" +
			"auto_response_enabled = true\n\n" +
			"[logging]\n" +
			"level = \"info\"\n\n" +
			"[quarantine]\n" +
			"dir = 'C:\\ProgramData\\EDRAgent\\quarantine'\n" +
			"\"@ | Set-Content $ConfigFile -Encoding UTF8\n\n" +
			"if (Get-Service -Name $SvcName -ErrorAction SilentlyContinue) {\n" +
			"    Stop-Service -Name $SvcName -Force -ErrorAction SilentlyContinue\n" +
			"    sc.exe delete $SvcName | Out-Null\n" +
			"    Start-Sleep -Seconds 2\n" +
			"}\n" +
			"$binPath = \"`\"$InstallDir\\edr-agent.exe`\" --config `\"$ConfigFile`\"\"\n" +
			"New-Service -Name $SvcName -BinaryPathName $binPath " + bq + "\n" +
			"    -DisplayName \"EDR Platform Agent\" -StartupType Automatic | Out-Null\n" +
			"Start-Service -Name $SvcName\n" +
			"Write-Host \"[+] サービスを開始しました\" -ForegroundColor Green\n" +
			"Write-Host \"[+] インストール完了\" -ForegroundColor Green\n"

		c.Header("Content-Type", "text/plain; charset=utf-8")
		c.Header("Content-Disposition", "inline; filename=Install-EDRAgent.ps1")
		c.String(http.StatusOK, script)

	default:
		c.JSON(http.StatusBadRequest, gin.H{
			"error": fmt.Sprintf("無効なOSです: %s (linux|windows|darwin)", osParam),
		})
	}
}
